"seed": 0
"backend": "python"
"preprocess_obs": False

# SCENARIO
"scenario": "Foraging"
"scenario_file": "foraging.py"
"num_agents": 3
"num_resources": 2
"max_steps": 100
"action_type": "Discrete"
"number_of_robots": 3
"controller": "clf_uni_position"
"barrier_fn": "robust_barriers"
"update_frequency": 30
heterogeneity: {
  "type": "capability_set",
  "obs_type": "full_capability_set",
  "values": [[1], [2], [3]],
  "sample": False,
}

# MODEL CONFIG
"input_dim": 18
"hidden_dim": 512
"output_dim": 5

# DEPLOYMENT CONFIG
"model_weights": "models/mappo/mappo_foraging.safetensors"
"model_file": "actor.py"
"model_class": RNNActorMAPPO
"save_gif": True
