"seed": 0
"backend": "python"
"preprocess_obs": False

# SCENARIO
"scenario": "MaterialTransport"
"scenario_file": "material_transport.py"
"num_agents": 4
"max_steps": 70
"action_type": "Discrete"
"number_of_robots": 4
"controller": "clf_uni_position"
"barrier_fn": "robust_barriers"
"update_frequency": 60
"heterogeneity": {
    "type": "capability_set",
    "obs_type": "full_capability_set",
    "values": [[.45, 5], [.45, 5], [.15, 15], [.15, 15]],
    "sample": False,
}
"zone1_dist": {
    "mu": 75,
    "sigma": 10,
}
"zone2_dist": {
    "mu": 15,
    "sigma": 4,
}
"step_dist": 1

# MODEL CONFIG
"input_dim": 22
"hidden_dim": 512
"output_dim": 5

# DEPLOYMENT CONFIG
"model_weights": "models/ippo/ippo_material_transport.safetensors"
"model_file": "actor.py"
"model_class": RNNActorIPPO
"save_gif": True
