"seed": 0
"backend": "python"
"preprocess_obs": False

# SCENARIO
"scenario": "RWARE"
"scenario_file": "rware.py"
"num_agents": 3
"num_cells": 6
"max_steps": 100
"action_type": "Discrete"
"number_of_robots": 3
"controller": "clf_uni_position"
"barrier_fn": "robust_barriers"
"update_frequency": 60

# MODEL CONFIG
"input_dim": 31
"hidden_dim": 256
"output_dim": 5

# DEPLOYMENT CONFIG
"model_weights": "models/pqn/pqn_vdn_rnn_rware.safetensors"
"model_file": "actor.py"
"model_class": RNNActorPQN
"save_gif": True
